[package]
name = "evaera/fabric"
version = "0.0.0"
author = "evaera"
content_root = "src"
license = "MIT"

[dependencies]
t = { git = "https://github.com/Roblox/t" }
TestEZ = { git = "https://github.com/Roblox/testez" }
Promise = { git = "https://github.com/evaera/roblox-lua-promise" }